package com.example.analytics

/** GA4 event names (≤40 chars). Recommended GA4 events keep Google's exact names. */
object Event {
    const val SCREEN_VIEW = "screen_view"
    const val DEEP_LINK_OPEN = "deep_link_open"
    const val NOTIFICATION_OPEN = "notification_open"
    const val NOTIFICATION_PERMISSION = "notification_permission"

    const val AUTH_START = "auth_start"
    const val AUTH_FALLBACK = "auth_fallback"
    const val AUTH_ERROR = "auth_error"
    const val LOGIN = "login"
    const val SIGN_UP = "sign_up"
    const val LOGOUT = "logout"
    const val ACCOUNT_DELETED = "account_deleted"
    const val KYC_START = "kyc_start"
    const val KYC_COMPLETE = "kyc_complete"

    const val SEARCH = "search"
    const val FILTER_APPLY = "filter_apply"
    const val FILTER_RESET = "filter_reset"
    const val MAP_TOGGLE = "map_toggle"
    const val VIEW_ITEM_LIST = "view_item_list"
    const val SELECT_ITEM = "select_item"
    const val VIEW_ITEM = "view_item"
    const val SELECT_ROOM = "select_room"
    const val VIEW_AVAILABILITY = "view_availability"
    const val ADD_TO_WISHLIST = "add_to_wishlist"
    const val REMOVE_FROM_WISHLIST = "remove_from_wishlist"
    const val SHARE = "share"
    const val GENERATE_LEAD = "generate_lead"
    const val CONTACT_SPECIALIST = "contact_specialist"

    const val BEGIN_CHECKOUT = "begin_checkout"
    const val BOOKING_SLOT_SELECT = "booking_slot_select"
    const val BOOKING_REQUEST = "booking_request"
    const val BOOKING_REQUEST_FAILED = "booking_request_failed"
    const val BOOKING_ACCEPTED = "booking_accepted"
    const val BOOKING_REJECTED = "booking_rejected"
    const val BOOKING_CANCELLED = "booking_cancelled"
    const val PAYMENT_ACKNOWLEDGED = "payment_acknowledged"
    const val PAYMENT_REMINDER_SENT = "payment_reminder_sent"
    const val CALENDAR_REMINDER_ADD = "calendar_reminder_add"

    const val LISTING_CREATE_START = "listing_create_start"
    const val LISTING_DRAFT_SAVED = "listing_draft_saved"
    const val LISTING_PUBLISH = "listing_publish"
    const val LISTING_PUBLISH_BLOCKED = "listing_publish_blocked"
    const val LISTING_UPDATE = "listing_update"
    const val LISTING_DELETE = "listing_delete"
    const val LISTING_STATUS_CHANGE = "listing_status_change"
    const val LISTING_VERIFICATION_REQUEST = "listing_verification_request"
    const val SUBDIVISION_ADD = "subdivision_add"
    const val SUBDIVISION_REMOVE = "subdivision_remove"
    const val LISTING_PRICE_CHANGE = "listing_price_change"
    const val BLACKOUT_ADD = "blackout_add"

    // ProHost Premium (Google Play is the billing authority). premium_purchase_success,
    // subscription_restored/renewed/expired are logged server-side (functions/src/billing).
    const val PREMIUM_PAGE_VIEWED = "premium_page_viewed"
    const val PREMIUM_PLAN_VIEWED = "premium_plan_viewed"
    const val PREMIUM_CHECKOUT_STARTED = "premium_checkout_started"
    const val PREMIUM_PURCHASE_FAILED = "premium_purchase_failed"
    const val PREMIUM_PURCHASE_PENDING = "premium_purchase_pending"
    const val PREMIUM_PLANS_LOAD_FAILED = "premium_plans_load_failed"
    const val PREMIUM_RESTORE_RESULT = "premium_restore_result"
    const val REDEEM_CODE_OPEN = "redeem_code_open"
    const val MANAGE_SUBSCRIPTION_OPEN = "manage_subscription_open"
    const val ORDER_HISTORY_OPEN = "order_history_open"

    const val ADMIN_ACTION = "admin_action"
    const val APP_ERROR = "app_error"
}

/** Parameter names (≤40 chars). */
object Param {
    const val SCREEN_NAME = "screen_name"
    const val SCREEN_CLASS = "screen_class"
    const val SOURCE = "source"
    const val TARGET = "target"
    const val NOTIFICATION_TYPE = "notification_type"
    const val GRANTED = "granted"
    const val METHOD = "method"
    const val ROLE = "role"
    const val FROM = "from"
    const val TO = "to"
    const val CODE = "code"
    const val SEARCH_TERM = "search_term"
    const val RESULT_COUNT = "result_count"
    const val FILTER_TYPE = "filter_type"
    const val VALUE_LABEL = "filter_value"
    const val VIEW = "view"
    const val COUNTRY = "country"
    const val ITEM_LIST_NAME = "item_list_name"
    const val ITEMS = "items"
    const val ITEM_ID = "item_id"
    const val ITEM_NAME = "item_name"
    const val ITEM_CATEGORY = "item_category"
    const val ITEM_CATEGORY2 = "item_category2"
    const val ITEM_CATEGORY3 = "item_category3"
    const val ITEM_CATEGORY4 = "item_category4"
    const val ITEM_CATEGORY5 = "item_category5"
    const val ITEM_VARIANT = "item_variant"
    const val ROOM_ID = "room_id"
    const val PRICE = "price"
    const val CURRENCY = "currency"
    const val VALUE = "value"
    const val INDEX = "index"
    const val SUBDIVISION_TYPE = "subdivision_type"
    const val OPEN_SLOT_COUNT = "open_slot_count"
    const val CONTENT_TYPE = "content_type"
    const val CHANNEL = "channel"
    const val STRATEGY = "strategy"
    const val SLOT_COUNT = "slot_count"
    const val ATTENDEE_COUNT = "attendee_count"
    const val PRICING_MODE = "pricing_mode"
    const val IS_REBOOK = "is_rebook"
    const val REASON = "reason"
    const val BY = "by"
    const val SUBDIVISION_COUNT = "subdivision_count"
    const val DIRECTION = "direction"
    const val AFFECTED_COUNT = "affected_count"
    const val UPDATED_NOW_COUNT = "updated_now_count"
    const val NEXT_TERM_COUNT = "next_term_count"
    const val KEPT_COUNT = "kept_count"
    const val HAS_ATTENDEE_PRICING = "has_attendee_pricing"
    const val PLAN = "plan"
    const val PRODUCT_ID = "product_id"
    const val PLANS_LOADED = "plans_loaded"
    const val TRANSACTION_ID = "transaction_id"
    const val RESPONSE_CODE = "response_code"
    const val RESULT = "result"
    const val ACTION = "action"
    const val AREA = "area"
}

/** User property names (≤24 chars). */
object UserProp {
    const val ROLE = "user_role"
    const val COUNTRY = "user_country"
    const val GOVERNORATE = "user_governorate"
    const val SPECIALTY = "specialty"
    const val KYC_COMPLETE = "kyc_complete"
    const val IS_VERIFIED = "is_verified"
    const val PLAN_ID = "plan_id"
    const val PLAN_STATUS = "plan_status"
    const val LISTING_COUNT = "listing_count_bucket"
    const val ACCOUNT_AGE = "account_age_bucket"
    const val SIGNUP_METHOD = "signup_method"
    const val BUILD_TYPE = "build_type"
    const val IS_DEMO = "is_demo"
}
