package com.example.data.billing

import android.text.TextUtils
import android.util.Base64
import android.util.Log
import java.security.InvalidKeyException
import java.security.KeyFactory
import java.security.NoSuchAlgorithmException
import java.security.PublicKey
import java.security.Signature
import java.security.SignatureException
import java.security.spec.InvalidKeySpecException
import java.security.spec.X509EncodedKeySpec

/**
 * Security utility class for Google Play Billing purchase verification.
 * Verifies the RSA signature generated by Google Play using the merchant Base64 public key.
 */
object PlayBillingSecurity {
    private const val TAG = "PlayBillingSecurity"
    private const val KEY_FACTORY_ALGORITHM = "RSA"
    private const val SIGNATURE_ALGORITHM = "SHA256withRSA"

    /**
     * Merchant Base64-encoded RSA public key from Google Play Console Licensing setup.
     */
    const val MERCHANT_BASE64_PUBLIC_KEY =
        "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvxC69c6k2zB5f294E5fCxXkQ16idMtN1qpjyzwUJ/3h0tmmMCxcue5Do22EWJTPqjWqgr8Ffd6Eec8ef9R3VA+AQw3VuVH/wdrBs781KUJ1Wj4e+ejhBqFrQfNlvbKrBeoNgbPsPhS41q9buMwb2DG0w2nKZVHTFLqLC7a4/DfnacadX3PyrAlnt4H2LC5ey19OhRDCNksAIC3xdDtIwSfMHRsPb8U1Y+M43SV/MFVAtWz+HbKny66wvi51r2v7aVd0otANV1F++zIr1v1H57KlDo/4qdUjf9LrPzu4g5cSOD0ReZboBO2WQZRUeKDRXVPno4zk0nN5vKMnEBMibNQIDAQAB"

    /**
     * Verifies that the data was signed with the given signature.
     *
     * @param signedData the signed data (JSON purchase payload)
     * @param signature the signature for the data
     * @return true if the signature is valid, false otherwise
     */
    fun verifyPurchase(signedData: String, signature: String): Boolean {
        if (TextUtils.isEmpty(signedData) || TextUtils.isEmpty(signature)) {
            Log.e(TAG, "Purchase verification failed: signedData or signature is empty")
            return false
        }
        val key = generatePublicKey(MERCHANT_BASE64_PUBLIC_KEY) ?: return false
        return verify(key, signedData, signature)
    }

    /**
     * Generates a PublicKey instance from a Base64-encoded string.
     */
    private fun generatePublicKey(encodedPublicKey: String): PublicKey? {
        return try {
            val decodedKey = Base64.decode(encodedPublicKey, Base64.DEFAULT)
            val keyFactory = KeyFactory.getInstance(KEY_FACTORY_ALGORITHM)
            keyFactory.generatePublic(X509EncodedKeySpec(decodedKey))
        } catch (e: NoSuchAlgorithmException) {
            Log.e(TAG, "RSA algorithm not supported", e)
            null
        } catch (e: InvalidKeySpecException) {
            Log.e(TAG, "Invalid key specification", e)
            null
        } catch (e: IllegalArgumentException) {
            Log.e(TAG, "Base64 decoding failed", e)
            null
        }
    }

    /**
     * Verifies that the signature matches the signed data using the public key.
     */
    private fun verify(publicKey: PublicKey, signedData: String, signature: String): Boolean {
        return try {
            val sig = Signature.getInstance(SIGNATURE_ALGORITHM)
            sig.initVerify(publicKey)
            sig.update(signedData.toByteArray())
            if (!sig.verify(Base64.decode(signature, Base64.DEFAULT))) {
                Log.e(TAG, "Signature verification failed.")
                false
            } else {
                true
            }
        } catch (e: NoSuchAlgorithmException) {
            Log.e(TAG, "SHA256withRSA algorithm not supported", e)
            false
        } catch (e: InvalidKeyException) {
            Log.e(TAG, "Invalid key exception", e)
            false
        } catch (e: SignatureException) {
            Log.e(TAG, "Signature exception", e)
            false
        } catch (e: IllegalArgumentException) {
            Log.e(TAG, "Base64 decoding failed", e)
            false
        }
    }
}
